# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b09be9fbb3b3c145ea6eab3f374cf872b4db11ec9b032a984b92f4ebd6836a0fe00990b2ce49b35658d66b6151809bfdd5832beab6aa942e9207b802a92d323

test:
  secret_key_base: 391a20faa85794680652c3c23a114326d573ac7b2df12d4117a4271e3fc4a13f4a7dbe251036ce79cd5d770cfc8063471105291765c4b7ec376469d561a1a37c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
